---
- name: Ansible Tutorial
  hosts: all
  become: true
  tasks:
    - name: Install apache2 and php packages for ubuntu
      package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: present
        update_cache: true
